services:
  discord-bot:
    build: .
    container_name: pfp_spy
    env_file:
      - .env
    volumes:
      - "./data:/app/data"
    restart: unless-stopped
    environment:
      - DATABASE_URL=/app/data/database.sqlite
